---
- name: check if current CPU has support for SSE 4.2
  shell: grep -q sse4_2 /proc/cpuinfo && echo "SSE 4.2 supported" || echo "SSE 4.2 not supported"

- name: add the Yandex repository
  become: yes
  lineinfile: dest="/etc/apt/sources.list" line="deb http://repo.yandex.ru/clickhouse/deb/stable/ main/" state=present

- name: apt upgrade
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 86400

- name: Add an apt key by id from a keyserver
  shell: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E0C56BD4

- name: Installing Prerequisites 
  become: yes
  apt: name={{item}} state=installed allow_unauthenticated=yes
  with_items:
    - 'dirmngr'
    - 'clickhouse-client'
    - 'clickhouse-server'

- name: Connect ClickHouse via clickhouse-client
  become: yes
  lineinfile:
    dest: "/etc/clickhouse-server/config.xml" 
    regexp: '    <!-- <listen_host>' 
    line: "    <listen_host>::</listen_host>"

- name: Start Click
  shell: sudo service clickhouse-server start

- name: chk conn
  shell: clickhouse-client -h '192.168.56.14' -q 'select 1'
