---
- name: apt upgrade
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 86400

- name: Installing Prerequisites 
  apt: name={{item}} state=installed
  with_items:
    - 'wget'
    - 'tar'
    - 'gzip'
    - 'unzip'
    - 'default-jdk'

- set_fact: work_dir="/home/hduser"
- set_fact: file_name=hadoop-3.1.2
- set_fact: full_name="{{work_dir}}/{{file_name}}"

#check if tar already exists
- stat: path="{{full_name}}.tar.gz"
  register: hadoop_tar

- name: Installing Hadoop
  become: yes
  get_url:
    url: https://www-us.apache.org/dist/hadoop/common/hadoop-3.1.2/{{file_name}}.tar.gz
    dest: "{{ work_dir }}"
  register: result
  until: result is success
  when: not hadoop_tar.stat.exists

- name: Unzip
  unarchive: 
    src: "{{full_name}}.tar.gz"
    dest: "{{ work_dir }}" 
    creates: "{{full_name}}"
    copy: no

- name: mv to /usr/local/hadoop
  synchronize:
    src: "{{full_name}}"
    dest: /usr/local/hadoop
  delegate_to: "{{ inventory_hostname }}"

#  copy:
#    src: "{{full_name}}"
#    dest: /usr/local/hadoop
#    remote_src: yes
#    directory_mode: yes

- name: remove ald folder
  file:
    path: "{{full_name}}"
    state: absent
