---
- name: Step 1 — Installing Prerequisites
  apt: name={{item}} state=installed
  with_items:
    - 'wget'
    - 'tar'
    - 'gzip'
    - 'unzip'
    - 'default-jdk'

- shell: java -version

- set_fact: work_dir="/home/vagrant"
- set_fact: file_name=hadoop-3.1.2
- set_fact: full_name="{{work_dir}}/{{file_name}}"
- stat: path="{{full_name}}.tar.gz"
  register: hadoop_tar

# - file:
#     path: "{{ work_dir }}"
#     state: directory
#     mode: 0755

- name: Step 2 — Installing Hadoop
  become: yes
  get_url:
    url: https://www-us.apache.org/dist/hadoop/common/hadoop-3.1.2/{{file_name}}.tar.gz
    dest: "{{ work_dir }}"
  register: result
  until: result is success
  when: not hadoop_tar.stat.exists

- name: Unzip
  unarchive: 
    src: "{{full_name}}.tar.gz"
    dest: "{{work_dir}}" 
    creates: "{{full_name}}"
    copy: no

- name: Step 3 — Configuring Hadoop's Java Home
  lineinfile: 
    path: "{{ full_name }}/etc/hadoop/hadoop-env.sh"
    state: present
    regexp: JAVA_HOME= 
    line: "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64"

- name: Step 4 — Running Hadoop
  shell: "{{ full_name  }}/bin/hadoop version"

