---
# tasks file for deploy_hadoop
- name: apt upgrade
    apt:
      upgrade: dist
      update_cache: yes
      cache_valid_time: 86400

  - name: install Apache
    apt: name={{item}} state=installed
    with_items:
      - 'python-pip'
      - 'apache2'
  
  - name: Start Apache
    service: name=apache2 state=started enabled=yes

  - shell: uptime
    register: results

  - debug:
      var: results.stdout