---
- include_tasks: infrastructure.yml

- include_tasks: ssh_keys.yml

- include_tasks: install.yml

- include_tasks: config.yml

- include_tasks: start.yml
#  when: not hadoop.stat.exists
#- include_tasks: ex_mapreduce.yml
