---
# tasks file for deploy_hadoop
- name: apt upgrade
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 86400

- stat: path=/etc/hadoop
  register: hadoop

- include_tasks: prereq_install.yml
  when: not hadoop.stat.exists

- shell: uptime
  register: results

- debug:
    var: results.stdout

