---
- name: ssh-keygen
  shell: > 
    ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
    creates="~/.ssh/id_rsa"

- name: fetch
  fetch: 
    src: "~/.ssh/id_rsa.pub"
    dest: "buffer/{{ansible_hostname}}-id_rsa.pub"
    flat: yes

- name: copy with authorized_key
  tags: runcd
  authorized_key:
    user: vagrant
    state: present
    key: "{{ lookup('file','buffer/{{item}}-id_rsa.pub')}}"
  when: "{{ item != ansible_hostname }}"
  with_items: 
    - "{{ groups['all'] }}"
